### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by lsamamig** [elad-bar/ha-dahuavto#5]
![error](https://user-images.githubusercontent.com/4015370/116990185-0fe9f580-acd3-11eb-8c77-5f2d843ea667.jpg)
I have no idea what to do next... :((((

----------------------------------------------------------------------------------------------------------------
Detalles de registro (ERROR)

Logger: custom_components.dahuavto.dahuavto_data
Source: custom_components/dahuavto/dahuavto_data.py:112
Integration: Dahua VTO Integration (documentation)
First occurred: 3 de mayo de 2021 21:05:11 (10264 occurrences)
Last logged: 11:20:51

    VTO Request to /cgi-bin/magicBox.cgi?action=getSystemInfo failed, Error: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/dahuavto/dahuavto_data.py, line 98: response = requests.get(url, timeout=5, auth=self._auth), Line: 98
    VTO Request to /cgi-bin/recordFinder.cgi?action=find&name=VideoTalkLog failed, Error: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/dahuavto/dahuavto_data.py, line 98: response = requests.get(url, timeout=5, auth=self._auth), Line: 98

-----------------------------------------------------------------------------------------------------------

**Comment by elad-bar** [comment]
This component is not maintained, you can use the DahuaVTO2MQTT as docker to receive MQTT message for events or open door
